from fyers_apiv3 import fyersModel


client_id = "QGP6MO6UJQ-100"
access_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIiwieDoyIl0sImF0X2hhc2giOiJnQUFBQUFCbl95cXhsSUlIT0UyZlJ3LVdNTU9peHhUXzU3alV6WERITlVhTE4yRmVKLXpjcldqMmc3cGNCd1ptN0cwSHM1VWVLMGhvek92cFhFbUZYaVp0Qm1iTWNYQlgwazhJNnZEYTkzSVhjSFE3MGFFRXVwdz0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiJkZWNhY2RhZDNmNzdjMGNkYTE0OThlNzY1MzdiMTMyYjcxNGMyZTg0NmQzNDFmMmZiYzkzZmY1YSIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiWFIyMDE4NSIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzQ0ODQ5ODAwLCJpYXQiOjE3NDQ3NzU4NTcsImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc0NDc3NTg1Nywic3ViIjoiYWNjZXNzX3Rva2VuIn0.jsrBoPkR_Rl4fp4dL_M-g94C32dO6OzoHFtEwTotNgI"
fyers = fyersModel.FyersModel(client_id=client_id, token=access_token,is_async=False, log_path="")

data = {
    "symbol":"NSE:NIFTY25APRFUT",
    "ohlcv_flag":"1"
}

response = fyers.depth(data=data)
print(response)
