from fyers_apiv3 import fyersModel

client_id = "QGP6MO6UJQ-100"
access_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIiwieDoyIl0sImF0X2hhc2giOiJnQUFBQUFCbl9reU4wMGh5SGwwdzdZbzQ5YzZPQmpSZjA4cFE0akZDLWpKSDNobDZoT2VZSkkxRy0yZ1VVQko4SThhU1BWbjJNUDZ1LTRkbXdUdGhWamtUZUN0MkR6TDRkeE8ydzlyYUdORjBsNGZPbjI2aEtLOD0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiJkZWNhY2RhZDNmNzdjMGNkYTE0OThlNzY1MzdiMTMyYjcxNGMyZTg0NmQzNDFmMmZiYzkzZmY1YSIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiWFIyMDE4NSIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzQ0NzYzNDAwLCJpYXQiOjE3NDQ3MTg5ODksImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc0NDcxODk4OSwic3ViIjoiYWNjZXNzX3Rva2VuIn0.ayLNhN8hOoB9FHunCm20P1WF4_BimeKX-Noepo71g0U"

fyers = fyersModel.FyersModel(client_id=client_id, is_async=False, token=access_token, log_path="")

data = {
    "symbols":"NSE:SBIN-EQ,NSE:IDEA-EQ"
}

response = fyers.quotes(data=data)
print(response)